BlogSiteProject/BlogSiteProject/Models/ErrorViewModel.cs
using System;

namespace BlogSiteProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogSiteProject/BlogSiteProject/Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogSiteProject.Models
{
    public class Kullanici
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }



        //Navigation Property

        public List<Makale> Makaleler { get; set; }
    }
}

BlogSiteProject/BlogSiteProject/Models/Makale.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogSiteProject.Models
{   
    public class Makale
    {
        public int MakaleID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }


        //Nav
        public int KullaniciID { get; set; }
        public Kullanici Kullanici { get; set; }
    }
}

BlogSiteProject/BlogSiteProject/Models/ViewModels/KullaniciMakaleVM.cs
using System.Collections.Generic;
using System.Linq;

namespace BlogSiteProject.Models.ViewModels
{
    public class KullaniciMakaleVM
    {
        public Kullanici Kullanici { get; set; }
        public IQueryable<Makale> Makaleler { get; set; }
    }
}

BlogSiteProject/BlogSiteProject/Controllers/HomeController.cs
using BlogSiteProject.Models;
using BlogSiteProject.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlogSiteProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IKullaniciRepository _kullaniciRepository;
        private readonly IMakaleRepository _makaleRepository;

        public HomeController(ILogger<HomeController> logger, IKullaniciRepository kullaniciRepository, IMakaleRepository makaleRepository)
        {
            _logger = logger;
            _kullaniciRepository = kullaniciRepository;
            _makaleRepository = makaleRepository;
        }

        public IActionResult Index()
        {
            IQueryable<Makale> makaleler = _makaleRepository.Makaleler.Include(x => x.Kullanici);
            return View(makaleler);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogSiteProject/BlogSiteProject/Controllers/KullaniciController.cs
using BlogSiteProject.Models;
using BlogSiteProject.Models.ViewModels;
using BlogSiteProject.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogSiteProject.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly IKullaniciRepository _kullaniciRepository;
        private readonly IMakaleRepository _makaleRepository;

        public KullaniciController(IKullaniciRepository kullaniciRepository, IMakaleRepository makaleRepository)
        {
            _kullaniciRepository = kullaniciRepository;
            _makaleRepository = makaleRepository;
        }
        public IActionResult Index()
        {
            return View(_kullaniciRepository.Kullanicilar);
        }
        public IActionResult KullaniciDetaylari(int id)
        {
            KullaniciMakaleVM vm = new KullaniciMakaleVM();
            vm.Kullanici = _kullaniciRepository.GetByID(id);
            vm.Makaleler = _makaleRepository.GetByKullaniciID(id);

            return View(vm);
        }
        public IActionResult KullaniciDuzenle(int id)
        {
            return View(_kullaniciRepository.GetByID(id));
        }
        [HttpPost]
        public IActionResult KullaniciDuzenle(Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                _kullaniciRepository.UpdateKullanici(kullanici);
            }
            return RedirectToAction("Index");
        }
        public IActionResult KullaniciSil(int id)
        {
            _kullaniciRepository.DeleteKullanici(id);
            return RedirectToAction("Index");
        }
        public IActionResult KullaniciEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult KullaniciEkle(Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                _kullaniciRepository.InsertKullanici(kullanici);
            }
            return RedirectToAction("Index");
        }
    }
}

BlogSiteProject/BlogSiteProject/Controllers/MakaleController.cs
using BlogSiteProject.Database;
using BlogSiteProject.Models;
using BlogSiteProject.Models.ViewModels;
using BlogSiteProject.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogSiteProject.Controllers
{
    public class MakaleController : Controller
    {
        private readonly IMakaleRepository _repo;
        private readonly IKullaniciRepository _kullaniciRepository;

        public MakaleController(IMakaleRepository makaleRepository, IKullaniciRepository kullaniciRepository)
        {
            _repo = makaleRepository;
            _kullaniciRepository = kullaniciRepository;
        }

        public IActionResult Index()
        {
            return View(_repo.Makaleler.Include(x=>x.Kullanici));
        }

        [HttpGet]
        public IActionResult MakaleEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult MakaleEkle(Makale makale)
        {
            if (ModelState.IsValid)
            {
                _repo.InsertMakale(makale);
            }
            return RedirectToAction("Index");
        }
        public IActionResult MakaleDetaylari(int id)
        {
            KullaniciMakaleVM vm = new KullaniciMakaleVM();
            vm.Kullanici = _kullaniciRepository.GetByID(id);
            vm.Makaleler = _repo.GetByKullaniciID(id);

            return View(vm);
        }

        public IActionResult MakaleSil(int id)
        {
            _repo.DeleteMakale(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult MakaleDuzenle(int id)
        {
            Makale duzenlenecekMakale = _repo.GetByID(id);
            return View(duzenlenecekMakale);
        }

        [HttpPost]
        public IActionResult MakaleDuzenle(Makale makale)
        {
            if (ModelState.IsValid)
            {
                _repo.UpdateMakale(makale);
            }
            return View(makale);
        }

    }
}

BlogSiteProject/BlogSiteProject/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="container mt-5">
    <h1>Every idea needs a <b>Burak, Furkan and Osman</b></h1>
    <br />
    <div class="row">
        <p class="col-lg-6">
            The best ideas can change who we are. Medium is where those ideas take shape, take off, and spark powerful conversations. We’re an open platform where over 100 million readers come to find insightful and dynamic thinking. Here, expert and undiscovered voices alike dive into the heart of any topic and bring new ideas to the surface. Our purpose is to spread these ideas and deepen understanding of the world.

            We’re creating a new model for digital publishing. One that supports nuance, complexity, and vital storytelling without giving in to the incentives of advertising. It’s an environment that’s open to everyone but promotes substance and authenticity. And it’s where deeper connections forged between readers and writers can lead to discovery and growth. Together with millions of collaborators, we’re building a trusted and vibrant ecosystem fueled by important ideas and the people who think about them.
        </p>
        <p class="col-lg-6">

            <img class="img-fluid" src="~/img/oldubu.jpg" />
        </p>
    </div>
</div>

BlogSiteProject/BlogSiteProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IQueryable<Makale>

@*<div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core%22%3Ebuilding Web apps with ASP.NET Core</a></p>
    </div>*@


<div class="row mh-100">
    <div class="position-absolute img-fluid" style="padding-top:150px; padding-left:50px;">
        <h1>Hello World</h1>
        <p><b>Discover stories, thinking, and expertise from writers on any topic.</b></p>
    </div>
    <img class="w-100 img-fluid" style="height:400px" src="~/img/sarısarııı.jpg">
</div>

<div class="container mt-5">
    @foreach (var makale in Model)
    {
    <dl class="row">
        <dt class="col-sm-2">
            Makale Yazarı Adı:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => makale.Kullanici.FirstName)  @Html.DisplayFor(model => makale.Kullanici.LastName)
        </dd>
        <dt class="col-sm-2">
            Başlık
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => makale.Title)
        </dd>
        <dt class="col-sm-2">
            İçerik
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => makale.Content)
        </dd>
        @*<dd class="col-sm-10">
            <a asp-controller="Makale" asp-action="MakaleDuzenle" asp-route-id="@makale.MakaleID">Düzenle</a> |
            <a asp-controller="Makale" asp-action="MakaleSil" asp-route-id="@makale.MakaleID">Sil</a>
        </dd>*@
    </dl>
        <hr />
        <br />
    }
</div>

BlogSiteProject/BlogSiteProject/Views/Kullanici/Index.cshtml
@model IEnumerable<BlogSiteProject.Models.Kullanici>

@{
    ViewData["Title"] = "Index";
}



<div class="m-5">
    <h1>Kullanıcılar</h1>

    <p>
        <a class="btn btn-primary" asp-action="KullaniciEkle">Yeni Kullanıcı</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Kullanıcı Adı
                </th>
                <th>
                    Kullanıcı Soyadı
                </th>
                <th>
                    İşlemler
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        <a asp-action="KullaniciDuzenle" asp-route-id="@item.ID">Düzenle</a> |
                        <a asp-action="KullaniciDetaylari" asp-route-id="@item.ID">Detaylar</a> |
                        <a asp-action="KullaniciSil" asp-route-id="@item.ID">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

BlogSiteProject/BlogSiteProject/Views/Kullanici/KullaniciDetaylari.cshtml
@model BlogSiteProject.Models.ViewModels.KullaniciMakaleVM

@{
    ViewData["Title"] = "UserDetails";
}
<div class="container mt-5">
    <h1>Kullanıcı Detayları</h1>

    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Kullanıcı Adı
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Kullanici.FirstName)
            </dd>
            <dt class="col-sm-2">
                Kullanıcı Soyadı
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Kullanici.LastName)
            </dd>
            <dt class="col-sm-2">
                Kullanıcı ID
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Kullanici.ID)
            </dd>
        </dl>

        <br />
        <h4>Makaleler</h4>
        <br />

        @foreach (var makale in Model.Makaleler)
        {
            <dl class="row">
                <dt class="col-sm-2">
                    Başlık
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => makale.Title)
                </dd>
                <dt class="col-sm-2">
                    İçerik
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => makale.Content)
                </dd>
                <dt class="col-sm-2">
                    İşlemler
                </dt>
                <dd class="col-sm-10">
                    <a asp-controller="Makale" asp-action="MakaleDuzenle" asp-route-id="@makale.MakaleID">Düzenle</a> |
                    <a asp-controller="Makale" asp-action="MakaleSil" asp-route-id="@makale.MakaleID">Sil</a>
                </dd>
            </dl>

            <hr />
            <br />
        }
    </div>
    <a asp-action="Index">Listeye Dön</a>
</div>

BlogSiteProject/BlogSiteProject/Views/Kullanici/KullaniciDuzenle.cshtml
@model BlogSiteProject.Models.Kullanici

@{
    ViewData["Title"] = "KullaniciDuzenle";
}

<div class="container mt-5">
    <h1>Kullanıcı Düzenle</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="KullaniciDuzenle">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">Adı</label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Soyadı</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Listeye Geri Dön</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogSiteProject/BlogSiteProject/Views/Kullanici/KullaniciEkle.cshtml
@model BlogSiteProject.Models.Kullanici

@{
    ViewData["Title"] = "KullaniciEkle";
}

<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

<div class="m-5">
    <h1>Kullanici Ekle</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="KullaniciEkle" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">Kullanıcı Adı</label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Kullanıcı Soyadı</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Oluştur" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Listeye Dön</a>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogSiteProject/BlogSiteProject/Views/Makale/Index.cshtml
@model IEnumerable<BlogSiteProject.Models.Makale>

@{
    ViewData["Title"] = "Makaleler";
}

<div class="m-5">
    <h1>Makaleler</h1>

    <p>
        <a asp-action="MakaleEkle" style="text-decoration:none;">Yeni Makale Ekle</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Başlık
                </th>
                <th>
                    İçerik
                </th>
                @*<th>
                    Yazar
                </th>*@
                <th>
                    İşlemler
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Kullanici.FirstName) @Html.DisplayFor(modelItem => item.Kullanici.LastName)
                </td>*@
                <td>
                    <a asp-action="MakaleDuzenle" asp-route-id="@item.MakaleID">Düzenle</a> |
                    <a asp-action="MakaleDetaylari" asp-route-id="@item.MakaleID">Detaylar</a> |
                    <a asp-action="MakaleSil" asp-route-id="@item.MakaleID">Sil</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

BlogSiteProject/BlogSiteProject/Views/Makale/MakaleDetaylari.cshtml
@model BlogSiteProject.Models.ViewModels.KullaniciMakaleVM

@{
    ViewData["Title"] = "MakaleDetaylari";
}

<div class="container mt-5">
    <h1>Makale Detaylari</h1>
    <hr />

    <div>
        <h5>Makale Yazarı</h5>
        <dl class="row">
            <dt class="col-sm-2">
                <partial>@Model.Kullanici.FirstName @Model.Kullanici.LastName</partial>
            </dt>
        </dl>
    </div>
    <hr />

    @foreach (var makale in Model.Makaleler)
    {
        <dl class="row">
            <dt class="col-sm-2">
                Başlık
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => makale.Title)
            </dd>
            <dt class="col-sm-2">
                İçerik
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => makale.Content)
            </dd>
            <dt class="col-sm-2">
                İşlemler
            </dt>
            <dd class="col-sm-10">
                <a asp-controller="Makale" asp-action="MakaleDuzenle" asp-route-id="@makale.MakaleID">Düzenle</a> |
                <a asp-controller="Makale" asp-action="MakaleSil" asp-route-id="@makale.MakaleID">Sil</a>
            </dd>
        </dl>

        <hr />
        <br />
    }
    <div>
        <a asp-action="Index">Listeye Geri Dön</a>
    </div>
</div>

BlogSiteProject/BlogSiteProject/Views/Makale/MakaleDuzenle.cshtml
@model BlogSiteProject.Models.Makale

@{
    ViewData["Title"] = "Makale Duzenle";
}

<div class="container">
    <h1>Makale Duzenle</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="MakaleDuzenle" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="MakaleID" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label">Makale Başlığı</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Content" class="control-label">Makale İçeriği</label>
                    <input asp-for="Content" class="form-control" />
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="KullaniciID" class="control-label"></label>
                    <select asp-for="KullaniciID" class="form-control" asp-items="ViewBag.KullaniciID"></select>
                    <span asp-validation-for="KullaniciID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Listeye Geri Dön</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogSiteProject/BlogSiteProject/Views/Makale/MakaleEkle.cshtml
@model BlogSiteProject.Models.Makale

@{
    ViewData["Title"] = "Makale Ekle";
}

<h1 class="m-5">Makale Ekle</h1>
<hr />
<div class="row">
    <div class="col-md-4 m-5">
        <form asp-action="MakaleEkle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Başlık</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label">İçerik</label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciID" class="control-label">Kullanici ID</label>
                <input asp-for="KullaniciID" class="form-control" />
                <span asp-validation-for="KullaniciID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Makale Ekle" class="btn btn-success" />
            </div>
            <div>
                @*<a asp-action="Edit" asp-route-id="@Model.">Edit</a> |*@
                @*<a asp-action="MakaleDetaylari" asp-route-id="@Model.MakaleID">Details</a> |*@
                @*<a asp-action="KullaniciSil" asp-route-id="@item.ID">Delete</a>*@
            </div>
        </form>
    </div>
</div>

<div class="m-5">
    <a asp-action="Index" style="text-decoration:none;">Listeye Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogSiteProject/BlogSiteProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medium</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="/img/5968885.png" style="height: 40px; width:auto;" /> Medium</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="KullaniciEkle">Kullanıcı Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="Index">Kullanıcı Bilgileri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Makale" asp-action="Index">Makaleler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">Hakkında</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <main role="main" class="pb-3">
        @RenderBody()
    </main>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BlogWebSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>